import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html>
        <body>
           <SidebarProvider>
             <AppSidebar />
                 <main>
                   <SidebarTrigger />
                   {children}
                 </main>
           </SidebarProvider>
        </body>
   </html>
  );
}
